import { Router } from "express";
import { z } from "zod";
import { requireAuth } from "../middleware/auth.js";
import { asyncHandler } from "../utils/errors.js";
import {
  cancelTask,
  createExportTask,
  getTaskForUser,
  listTasks,
  retryTask
} from "../services/tasks.js";
import { serializeTask } from "../utils/serializers.js";
import { prisma } from "../config/prisma.js";
import { HttpError } from "../utils/errors.js";

const router = Router();
router.use(requireAuth);

router.get(
  "/",
  asyncHandler(async (req, res) => {
    const tasks = await listTasks(req.tenantId);
    res.json({ tasks: tasks.map(serializeTask) });
  })
);

router.post(
  "/",
  asyncHandler(async (req, res) => {
    const task = await createExportTask({
      tenantId: req.tenantId,
      userId: req.user.id,
      body: req.body
    });
    res.status(201).json({ task: serializeTask(task) });
  })
);

router.post(
  "/:id/cancel",
  asyncHandler(async (req, res) => {
    const task = await cancelTask(req.tenantId, req.params.id, {
      id: req.user.id,
      role: req.membership.role
    });
    res.json({ task: serializeTask(task), message: "取消请求已受理；已结算结果不会被抹掉或重复扣减" });
  })
);

router.post(
  "/:id/retry",
  asyncHandler(async (req, res) => {
    const task = await retryTask(req.tenantId, req.params.id, {
      id: req.user.id,
      role: req.membership.role
    });
    res.json({ task: serializeTask(task), message: "旧预留已释放，重试已重新预留" });
  })
);

router.get(
  "/:id/download",
  asyncHandler(async (req, res) => {
    const task = await getTaskForUser(req.tenantId, req.params.id);
    if (task.status !== "SUCCEEDED" || !task.resultName) {
      throw new HttpError(409, "只有成功任务可以下载，且下载地址必须通过当前租户授权");
    }
    res.setHeader("Content-Type", "text/plain; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="${encodeURIComponent(task.resultName)}"`);
    res.send(
      [
        `Project: ${task.project?.name || task.projectId}`,
        `Tenant: ${req.membership.tenant.name}`,
        `Task: ${task.id}`,
        `Estimated units: ${task.estimatedUnits}`,
        `Actual units: ${task.actualUnits}`,
        "This file is generated by the authenticated export service.",
        "It is not a public object-storage link."
      ].join("\\n")
    );
  })
);

export default router;
